version: "2"
services:
  julia_forest:
    image: julia_env_image
    container_name: julia_env_container
    build: .
    volumes:
      - ./learning_space:/works/learning_space
      - ./learning_space_notebook:/works/learning_space_notebook
    ports:
      - "8004:8004"
    tty: true
    command: jupyter notebook --port 8004 --ip=0.0.0.0 --allow-root --NotebookApp.token=''
# jupyter notebook --port 8004 --ip=0.0.0.0 --allow-root
